apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: ${CLUSTER_NAME}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: docker.io/ubuntu:jammy
        command:
          - sh
          - -c
          - echo "starting db migration"
          - sleep 60s
          - echo "completed db migration"
